### ISSUE TITLE
iOS client no longer working with demo app

### ISSUE THREAD

**Issue by dbadia** [dbadia/sqrl-server-base#4]
https://sqrl.grc.com/threads/login-fails.492/post-4934

**Comment by dbadia** [comment]
Was able to reproduce, need to look into this log message

2019-05-23 00:17:41 [https-jsse-nio-20000-exec-4] WARN  c.g.s.backchannel.SqrlClientRequest - "Jeff Arthur iOS SQRL Client @wuftmergufty 1.0.281 (8362)" Server parrot mismatch: Expected=dmVyPTENCm51dD1BbEE4d0J1MWVtU3hqUkhSVUFURWo4QWtqR2ppQUR0Nm8wZjlyWXZDUHFFSTF5ZlhwSm9wZGJFY0ZpNXJyNDhzUXN4T054QllFQjJFVTM1QVZ2SHRnTXY0N1ZVZUt3VDVuR2cxZ0NlSGduN2hHQWZUT1NISlBnDQp0aWY9MA0KcXJ5PS9zcXJsZXhhbXBsZS9zcXJsYmM_bnV0PUFsQTh3QnUxZW1TeGpSSFJVQVRFajhBa2pHamlBRHQ2bzBmOXJZdkNQcUVJMXlmWHBKb3BkYkVjRmk1cnI0OHNRc3hPTnhCWUVCMkVVMzVBVnZIdGdNdjQ3VlVlS3dUNW5HZzFnQ2VIZ243aEdBZlRPU0hKUGcmY29yPTdSUklSeDN3RjdXMzZONy0zc21Tb1NqMk5fRnhWbFd6VG9vbllmNzkzZEUNCg, Received=c3FybDovL3NxcmxqYXZhLmNvbToyMDAwMC9zcXJsZXhhbXBsZS9zcXJsYmM_bnV0PUFyckN3ZEtrcjJ5NC0zWDJXVV9fU256YjR1dUIyckNpSU5ldndvMUx3ZkJDbG5JNS1hdGxwR3A5UVdPS2lYUVBFc2tiamZJeDhsY0ZYdkNjbVhNMVFUUFJJWDhYcFRucDN2cVRjVEk2QkdZYlFJLXFDVkxmTDFzJmNvcj03UlJJUngzd0Y3VzM2TjctM3NtU29TajJOX0Z4VmxXelRvb25ZZjc5M2RF
2019-05-23 00:17:41 [https-jsse-nio-20000-exec-4] ERROR c.g.s.SqrlServerOperations - "Jeff Arthur iOS SQRL Client @wuftmergufty 1.0.281 (8362)" Received invalid SQRL request: "Jeff Arthur iOS SQRL Client @wuftmergufty 1.0.281 (8362)" Server parrot mismatch, possible tampering of sqrlClientOnRequest "Jeff Arthur iOS SQRL Client @wuftmergufty 1.0.281 (8362)" params: nut=[ArrCwdKkr2y4-3X2WU__Snzb4uuB2rCiINevwo1LwfBClnI5-atlpGp9QWOKiXQPEskbjfIx8lcFXvCcmXM1QTPRIX8XpTnp3vqTcTI6BGYbQI-qCVLfL1s]   cor=[7RRIRx3wF7W36N7-3smSoSj2N_FxVlWzToonYf793dE]   client=[dmVyPTENCmNtZD1xdWVyeQ0KaWRrPXlBZ3lSSU9tY25zbkt1bXRBT0JUY3VrWTJ2S2V3d1F6WV9wZ3JMeUJ2cjQNCm9wdD1jcHMNCg]   server=[c3FybDovL3NxcmxqYXZhLmNvbToyMDAwMC9zcXJsZXhhbXBsZS9zcXJsYmM_bnV0PUFyckN3ZEtrcjJ5NC0zWDJXVV9fU256YjR1dUIyckNpSU5ldndvMUx3ZkJDbG5JNS1hdGxwR3A5UVdPS2lYUVBFc2tiamZJeDhsY0ZYdkNjbVhNMVFUUFJJWDhYcFRucDN2cVRjVEk2QkdZYlFJLXFDVkxmTDFzJmNvcj03UlJJUngzd0Y3VzM2TjctM3NtU29TajJOX0Z4VmxXelRvb25ZZjc5M2RF]   ids=[QCMo4ebxQtbA7SorP2Cipk-wPJ0m0ADShzbDfNQAJh7vExbgDVBHFNf3rYwlbIZm8mmJ3453rIvyQ_KssiEKDg]
com.github.sqrlserverjava.exception.SqrlInvalidRequestException: "Jeff Arthur iOS SQRL Client @wuftmergufty 1.0.281 (8362)" Server parrot mismatch, possible tampering
        at com.github.sqrlserverjava.backchannel.SqrlClientRequest.<init>(SqrlClientRequest.java:141)
        at com.github.sqrlserverjava.SqrlClientFacingOperations.handleSqrlClientRequest(SqrlClientFacingOperations.java:112)
        at com.github.sqrlserverjava.example.sqrl.SqrlBackchannelServlet.doPost(SqrlBackchannelServlet.java:42)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.github.sqrlserverjava.example.ui.NoCacheServletFilter.doFilter(NoCacheServletFilter.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by dbadia** [comment]
Current iOS client shows a pop up stating "Response body is not application/x-www-form-urlencoded
".  Implemented a work around, will test shortly
